<a href="https://colab.research.google.com/github/ragib2002/data-science/blob/main/numpy_book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
#Performance difference

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%timeit my_arr2 = my_arr * 2

1.18 ms ± 208 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit my_list2 = my_list * 2

20 ms ± 2.69 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
arr = np.array([[1,3],[2,4]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr3 = np.zeros((3,5))

In [ ]:
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4 = arr.astype(np.float64)

In [ ]:
arr4

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
#array does not copy value when slicing

arr = np.array([1,2,3,4,5])
arr_s = arr[2:5]
print(arr_s)

[3 4 5]


In [5]:
#bare : assigns all elements of an array
arr_s[:] = 50
print(arr)

[ 1  2 50 50 50]


In [7]:
#If we want to create a new copy we have to use .copy()
arr2 = arr[2:5].copy()
print(arr2)

[50 50 50]


In [18]:
#another way of numpy array indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[1, 1]

5

In [13]:
#slicing (multi-dimention)
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [14]:
#boolean indexing
arr = np.array([2,3,4,5,6])
boo = np.array([True,False,True,False,True])
arr[boo]

array([2, 4, 6])

In [16]:
#boolean operations
print(~boo)
print(boo | boo)
print(boo & boo)

[False  True False  True False]
[ True False  True False  True]
[ True False  True False  True]


In [17]:
arr[arr > 4]

array([5, 6])

In [20]:
#fancy indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = arr[[0,2]]
arr2

array([[1, 2, 3],
       [7, 8, 9]])